<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actividad No Planeada' => '',
    'Activo' => '',
    'Actualizar' => '',
    'Are you sure you want to delete this item?' => '',
    'Artefacto' => '',
    'Bitacora de Tiempos' => '',
    'Bitacoratiempos' => '',
    'Crear' => '',
    'Crear Proyecto' => '',
    'Crear Registro' => '',
    'Crear registro' => '',
    'Delete' => '',
    'Fecha' => '',
    'Hora Final' => '',
    'Hora Inicio' => '',
    'Id Actividad Planeada' => '',
    'Id Bitacora Tiempo' => '',
    'Id Proyecto' => '',
    'Id Proyectos' => '',
    'Id Usuario' => '',
    'Interrupcion' => '',
    'Modificar Registro: ' => '',
    'Modificar {modelClass}: ' => '',
    'Nombre Proyecto' => '',
    'Proyectos' => '',
    'Reset' => '',
    'Search' => '',
    'Total' => '',
    'Update' => '',
];
